services:
  - type: web
    name: go-mailing-api
    env: go
    plan: free
    buildCommand: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o app cmd/server/main.go && ls -la
    startCommand: ./app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: SMTP_MAX_EMAILS_PER_HOUR
        sync: false
      - key: SMTP_MAX_EMAILS_PER_DAY
        sync: false
      - key: LOG_DATE_FORMAT
        value: hour-minute
      - key: LOG_ROUTE
        value: false
      - key: LOG_HEADERS
        value: false
      - key: LOG_BODY
        value: false
      - key: LOG_QUERIES
        value: false
      - key: LOG_RESPONSE
        value: false
